In [1]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:

import pandas as pd
data={
    'id':['1','2','3'],
    'name':['ananad','prabhu','bhuvanesh']
}
print(pd.DataFrame(data,index=[1,2,3]))

  id       name
1  1     ananad
2  2     prabhu
3  3  bhuvanesh


In [28]:
8
import pandas as pd
arr = np.random.randint(100, 1999, size=(1000, 100))
print(arr)
print(arr.shape)
df = pd.DataFrame(arr)

print(df[:9].tail(10))


[[ 458 1617  711 ... 1149 1651 1736]
 [1565  107 1359 ...  419 1336 1502]
 [ 781  988 1693 ... 1449  489 1268]
 ...
 [1089 1398 1710 ... 1622 1245 1973]
 [1867  224 1908 ... 1433 1193 1832]
 [1954 1128 1634 ...  328 1234 1770]]
(1000, 100)
     0     1     2     3     4     5     6     7     8     9   ...    90  \
0   458  1617   711   548   743  1090  1400   271   545   809  ...   253   
1  1565   107  1359   605   455  1618  1169   591   104  1001  ...   255   
2   781   988  1693   773   612  1024   541  1454   243   649  ...   221   
3  1407  1888  1479   158  1172   683   941  1148  1960   547  ...   250   
4  1732   497  1620   811   534  1075   255  1671   349  1330  ...  1715   
5   431  1470  1177   994   227  1071   186  1139  1134  1510  ...  1711   
6   957   660   669  1528   234  1063  1080  1851   944  1693  ...  1629   
7  1277   641   261   555  1727   881  1229   816   953   314  ...  1673   
8  1739  1833  1340  1811   841   995   558  1652  1175   970  ...   851   


In [13]:
def add_without_plus(a, b):
    while b != 0:
        # carry now contains common set bits of a and b
        carry = a & b
        
        # sum of bits of a and b where at least one of the bits is not set
        a = a ^ b
        
        # carry is shifted by one so that adding it to a gives the required sum
        b = carry << 1
    
    return a
# Example usage
num1 = int(input())
num2 = int(input())
result = add_without_plus(num1, num2)
print(f"The sum of {num1} and {num2} is {result}")

The sum of 9 and 9 is 18


In [17]:
import numpy as np
import pandas as pd
n=np.array(1,2,3,4,4,5)
mean=pd.stdev(n)
print(mean)


TypeError: array() takes from 1 to 2 positional arguments but 6 were given

In [60]:
a=8987
print(bin(a)[8:])

00011011


In [ ]:
import numpy as np
import pandas as pd
x=[1,2,3,4]
y=pd.Dataframe(x)
z=y.describe()
print(z)

: 